"""Add database indexes for performance optimization

Revision ID: 79e2ac959f72
Revises: 
Create Date: 2025-08-03 04:36:21.329006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79e2ac959f72'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_delivery_receipts_created_at', 'delivery_receipts', ['created_at'], unique=False)
    op.create_index('idx_delivery_receipts_status_created', 'delivery_receipts', ['status', 'created_at'], unique=False)
    op.create_index('idx_delivery_receipts_user_status', 'delivery_receipts', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_delivery_receipts_status'), 'delivery_receipts', ['status'], unique=False)
    op.create_index('idx_tasks_created_at', 'tasks', ['created_at'], unique=False)
    op.create_index('idx_tasks_status_created', 'tasks', ['status', 'created_at'], unique=False)
    op.create_index('idx_tasks_tracking_number', 'tasks', ['tracking_number'], unique=False)
    op.create_index('idx_tasks_user_status', 'tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index('idx_tracking_info_created_at', 'tracking_info', ['created_at'], unique=False)
    op.create_index('idx_tracking_info_signed_update', 'tracking_info', ['is_signed', 'last_update'], unique=False)
    op.create_index('idx_tracking_info_status_update', 'tracking_info', ['current_status', 'last_update'], unique=False)
    op.create_index('idx_tracking_info_updated_at', 'tracking_info', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tracking_info_current_status'), 'tracking_info', ['current_status'], unique=False)
    op.create_index(op.f('ix_tracking_info_last_update'), 'tracking_info', ['last_update'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tracking_info_last_update'), table_name='tracking_info')
    op.drop_index(op.f('ix_tracking_info_current_status'), table_name='tracking_info')
    op.drop_index('idx_tracking_info_updated_at', table_name='tracking_info')
    op.drop_index('idx_tracking_info_status_update', table_name='tracking_info')
    op.drop_index('idx_tracking_info_signed_update', table_name='tracking_info')
    op.drop_index('idx_tracking_info_created_at', table_name='tracking_info')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index('idx_tasks_user_status', table_name='tasks')
    op.drop_index('idx_tasks_tracking_number', table_name='tasks')
    op.drop_index('idx_tasks_status_created', table_name='tasks')
    op.drop_index('idx_tasks_created_at', table_name='tasks')
    op.drop_index(op.f('ix_delivery_receipts_status'), table_name='delivery_receipts')
    op.drop_index('idx_delivery_receipts_user_status', table_name='delivery_receipts')
    op.drop_index('idx_delivery_receipts_status_created', table_name='delivery_receipts')
    op.drop_index('idx_delivery_receipts_created_at', table_name='delivery_receipts')
    # ### end Alembic commands ###
